version: "3"

volumes:
  pgdata:

services:
  credit_assistance:
    restart: always
    container_name: credit_assistance
    build: .
    ports:
      - '80:80'
    depends_on:
      - postgres
      - pgadmin
    volumes:
      - .:/code
    environment:
      - PYTHONPATH=/code
  postgres:
    restart: always
    container_name: postgres_container
    image: postgres:latest
    expose:
      - 5432
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./src/init.sql:/docker-entrypoint-initdb.d/init.sql
  pgadmin:
    restart: always
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '5050:80'